### ISSUE TITLE
Feed in edge weights from head to TCN

### ISSUE THREAD

**Issue by klieret** [gnn-tracking/gnn_tracking#128]
Feed in edge weights into MLP feeding into IN steps of TCN

**Comment by klieret** [comment]
![image](https://user-images.githubusercontent.com/13602468/196015578-f0c70ea2-0e21-4116-86cf-7a9e7d8b3eae.png)

**Comment by GageDeZoort** [comment]
I guess the complication here is that calculating the edge weights "bottlenecks" the information you get from the network, so we could both calculate edge weights and reject bad edges _and_ propagate the edge features through an MLP to receive a more complicated set of features? It's at least worth trying.

**Comment by klieret** [comment]
Also see #130

**Comment by klieret** [comment]
Already implemented (and toggleable)
