### ISSUE TITLE
Move test files out of main code

### ISSUE THREAD

**Issue by klieret** [gnn-tracking/gnn_tracking#253]
Currently, all unit tests are included as `test_...` files with the rest of the code (in `src/gnn_tracking`). Instead they should be moved to a separate `test` directory like so:

```
project/
│
├── src/
│   └── gnn_tracking/
│
└── tests/
    ├── __init__.py
    └── test_1.py
```

**Comment by ameya1101** [comment]
Hi Kilian, do you think I could take a stab at this?

**Comment by klieret** [comment]
Sure, go for it!
