### ISSUE TITLE
IOPub data rate exceeded error on jupyter notebook

### ISSUE THREAD

**Issue by Devdoot57** [gnn-tracking/gnn_tracking#353]
Training a model on the jupyter-notebook using `pytorch_lightning.Trainer` sometimes throws the following error-
```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
```

**Comment by klieret** [comment]
Can you try with `callbacks=[TQDMProgressBar(refresh_rate=5)]` (or an even higher refresh rate)? See [here](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.TQDMProgressBar.html#lightning.pytorch.callbacks.TQDMProgressBar). 

If you don't need the validation printout, you can simply remove the new `PrintValidationMetrics()` callback introduced in https://github.com/gnn-tracking/gnn_tracking/pull/354. Or, if your epochs run very fast, you could set `sample_size=2000` or something in the `TrackingDataModule` (this will oversample the training data).
