### ISSUE TITLE
Masking of PIDs for non-reconstructable

### ISSUE THREAD

**Issue by klieret** [gnn-tracking/gnn_tracking#59]
Currently we mask PIDs for testing but not for training. There was a comment in the code to rethink this but it will disappear with #43.

**Comment by GageDeZoort** [comment]
There are a lot of related issues here. Reconstructable particles will be whatever we hope to be able to reconstruct - e.g. particles with >2 layers hit that don't skip a layer. I have a feeling this is all we'd want to train on. For testing, we might want to report model performance with respect to all particles and with respect to reconstructable particles.

**Comment by klieret** [comment]
Ah, I actually saw that right now testing doesn't actually make any use of the PID information anyway. We probably need to add some more figures of merit there anyway.
